/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      // ─── Color Tokens (1:1 migration from static HTML Tailwind config) ───
      colors: {
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#b3c6f8',
        'on-error': '#ffffff',
        'on-surface-variant': '#5c403d',
        'sidebar-dark': '#0F172A',
        'on-primary-fixed-variant': '#93000f',
        'border-light': '#E2E8F0',
        'inverse-surface': '#233144',
        'on-secondary-container': '#435581',
        'surface-variant': '#d5e3fc',
        'on-tertiary-fixed-variant': '#004c6e',
        'tertiary': '#005a82',
        'on-primary': '#ffffff',
        'secondary-container': '#b9cbfe',
        'on-primary-container': '#ffebe9',
        'surface-container-highest': '#d5e3fc',
        'primary-container': '#d22528',
        'on-tertiary-fixed': '#001e2f',
        'on-primary-fixed': '#410003',
        'surface-tint': '#bd111c',
        'surface-container': '#e6eeff',
        'tertiary-fixed': '#c9e6ff',
        'on-background': '#0d1c2e',
        'surface-container-high': '#dce9ff',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#d9e2ff',
        'on-tertiary': '#ffffff',
        'primary-fixed-dim': '#ffb3ac',
        'surface-dim': '#ccdbf3',
        'on-surface': '#0d1c2e',
        'outline': '#906f6c',
        'tertiary-container': '#0074a6',
        'on-tertiary-container': '#e4f2ff',
        'surface-container-low': '#eff4ff',
        'on-error-container': '#93000a',
        'inverse-primary': '#ffb3ac',
        'background-subtle': '#F8FAFC',
        'secondary': '#4b5e8a',
        'surface': '#f8f9ff',
        'tertiary-fixed-dim': '#89ceff',
        'background': '#f8f9ff',
        'on-secondary-fixed-variant': '#334670',
        'inverse-on-surface': '#eaf1ff',
        'error': '#ba1a1a',
        'primary': '#ad0014',
        'on-secondary-fixed': '#021943',
        'surface-bright': '#f8f9ff',
        'primary-fixed': '#ffdad6',
        'error-container': '#ffdad6',
        'success-green': '#1FB07E',
        'outline-variant': '#e5bdb9',
      },

      // ─── Border Radius ─────────────────────────────────────────────────
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },

      // ─── Spacing ───────────────────────────────────────────────────────
      spacing: {
        'container-max': '1280px',
        'gutter': '24px',
        'margin-desktop': '40px',
        'margin-mobile': '16px',
        'unit': '4px',
      },

      // ─── Font Families ─────────────────────────────────────────────────
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'mono-code': ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
      },

      // ─── Font Sizes ────────────────────────────────────────────────────
      fontSize: {
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'mono-code': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
};
